### ISSUE TITLE
to:SKTagView性能问题： 在tableview中使用，cell复用后性能似乎非常差 

### ISSUE THREAD

**Issue by btxkenshin** [shiweifu/SFTagView#3]
RT,测试数据，每行大概有5-10个tag，滚动明显卡顿

测试环境：设备iPhone6 系统：iOS8
以下为步骤
1. 使用autolayout布局 
2. cell使用自动计算高度，即

```
tableView.rowHeight = UITableViewAutomaticDimension 
tableView.estimatedRowHeight = 100.0 
```
1. cellForRowAtIndexPath中每次先remov所有tag再重新添加 

```
        self.tagView.removeAllTags()

        var count:Int = tagArr.count - 1
        for i in 0...count {
            var tag:SKTag = SKTag(text: tagArr[i])
            tag.textColor = UIColor.whiteColor()
            tag.bgColor = UIColor.blueColor()
            tag.padding = UIEdgeInsets(top: 7, left: 20, bottom:7, right: 20)
            tag.fontSize = 16
            self.tagView.addTag(tag)
        }

```

**Comment by zsk425** [comment]
@btxkenshin 
谢谢你的反馈，不过你发错地方了。

针对你的情况，建议你使用SFTagView，或者其他控件。SKTagView内部布局也是用的Auto Layout，其实Auto Layout根本不适合处理tag这样的场景，之前的方案不是用的CollectionView就是手动布局(或许也可以用WebView试一下)，而SKTagView为了可以使用Auto Layout加重了性能开销，不适合在多个cell中使用。所以建议你尝试其他方案。

**Comment by shiweifu** [comment]
@btxkenshin 
我close了啊

**Comment by zsk425** [comment]
@shiweifu 

不好意思乱入了

**Comment by btxkenshin** [comment]
@zsk425 嗯，确实如此，即使使用CollectionView布局，其实也很难真正复用，性能上也是有问题的，只能自己实现tagcontentview的复用，谢
